spring:
  application:
    name: springboot-dubbo
dubbo:
  application:
    name: springboot-provider
    id: springboot-provider
  protocol:
    name: dubbo
    port: 20880
  registry:
    address: zookeeper://127.0.0.1:2181


demo:
  service:
    version: 1.0.0
