dubbo:
  cloud:
    subscribed-services: spring-cloud-dubbo-sample

spring:
  application:
    name: spring-cloud-dubbo-consumer
  cloud:
    zookeeper:
      connect-string: 127.0.0.1:2181
      discovery:
        register: false
